batch_size: 128
epochs: 50
lr: 0.001

device: mps
num_workers: 4
seed: 1234
use_wandb: False

data_dir: "/Volumes/SanDisk Extreme 55AE Media/data-omni"

# Evaluation
model_path: 

# L1 normalization
alpha: 1e-5

# patience for early stopping
patience: 5

# 